# Change these first
owner: luucyadmin # Your GitHub organization or username, where this repository lives
repo: luucy-status # The name of this repository

sites:
  - name: LUUCY
    url: https://app.luucy.ch

status-website:
  cname: status.luucy.ch
  baseUrl: /luucy-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LUUCY
  introTitle: ""
  introMessage: This is a status page for LUUCY
  navbar:
    - title: Status
      href: /
    - title: Back to LUUCY
      href: https://app.luucy.ch/workspaces
